### PR TITLE
time travel restore

### PR DESCRIPTION
**Pull request by pivnicek**
ref: https://github.com/keboola/connection/issues/1040

Adds a selection in the Actions menu to create table from timestamp

Remaining TODOs:
- [x] update default filename on datetime select  
- [x] fix datetime input format
- [x] use project dataRetentionTime setting to determine calendar enabled dates
- [ ] allow text edit of date-time input

### CODE REVIEW

**Comment by ondrejhlavacek** [comment]
image

I am not sure about the 2 labels (Into Bucket, Table Name). They seem "too long" (but Replication Date does not) or inaccurate, but not too sure what to do. 

Create table from snapshot uses this form

image

so at least I'd stick to same names. If it is in the scope of this PR, do you think you could fix the Create table from snapshot input fields and labels, so that they are more similar to your version (`Destination bucket` => `Destination Bucket` & no line break, bucket dropdown, bucket and table name input widths).

**Comment by Halama** [comment]
@ondrejhlavacek Neni nahodou ten prvni screen z lokalni verze a druhy z produkce? Ono to ma na produkci trochu jine styly takze to vypada jinak.
V DEV oboji vypada takhle:
image


image

**Comment by Halama** [comment]
Ale fixuju to na:
image

**Comment by ondrejhlavacek** [comment]
@Halama jo, tak to je možný, to mě nenapadlo

**Comment by Halama** [comment]
Ještě jsem tam udělal pár úprav.

## Restore Table Modal

- říká jáká je retence dat
- Nabízí jenom data která jsou v intervalu retence nebo novější od založení tabukly
- Defaultně je předvybráno nejmenší datum
- Nezobrazuje se tam info o TZ, vše v UI je v aktuální TZ uživatele

image

## Snapshot & Restore

- Přidal jsem Time Travel Restore do sekce snapshotů
- Odebral jsem možnost Rollback která pro SNFLK a Redshift byla šedivá, a MySQL projekty už neexistují https://github.com/keboola/connection/issues/1179

image

**Comment by Halama** [comment]
@pivnicek may I ask you for check? thanks

**Comment by pivnicek** [comment]
@Halama code looks good, thanks for the updates!  I'm going to give it a test-drive now.

One thing about the `Snapshot and Restore` tab.  It's not immediately clear what is in the table (I know of course that they are snapshots:) but maybe the table should be inside the snapshot panel?

**Comment by Halama** [comment]
Yes, you are right about that content of table

**Comment by Halama** [comment]
What about this? 
image

**Comment by pivnicek** [comment]
hmm, better I think, but I'm not really sure.  I think this may be a question for jack:).  We can always update it easily later.

I tried it out though, and it seems to work great 👍.

only thing I'd change is the text in the modal to `... your project limit of 7 days`

**Comment by Halama** [comment]
thanks, I've pushed the fixes.
This is low-level almost deprecated console, so I think we should focus Jacks attention to new console.

**Comment by Halama** [comment]
And it is hidden in table detail, so I think we can release it?
I was also thinking about wording between `Time travel restore` and `Point in time restore`, but I think current one copied from Snowflake should be ok...

**Comment by pivnicek** [comment]
Yeah, I agree, I think it's fine. diky moc! 👍

**Pull request merged**
