### PR TITLE
link to new tokens ui

### PR DESCRIPTION
**Pull request by Halama**
V interní verzi tam půjde v horním menu ještě vidět link na Tokens.

image

image

### CODE REVIEW

**Comment by Halama** [comment]
@odinuv @kacurez mrknete prosim

**Comment by kacurez** [comment]
mozno by som dopisal This section is deprecated and will be removed soon.

**Comment by Halama** [comment]
upravil jsem na `This section is deprecated and will be removed soon. Please use new tokens management.` Mozna ma byt `the new tokens management`?

**Comment by Halama** [comment]
image

**Pull request merged**
