### PR TITLE
Fix - wait for files

### LINKED ISSUE #59: Can't download sliced file
Clicking the `Prepare Package` button does not download the file

image

### PR DESCRIPTION
**Pull request by Halama**
FIXES #59

### CODE REVIEW

**Comment by pivnicek** [comment]
aha, https://keboola.slack.com/archives/C09U3R1J4/p1534502409000100

**Comment by Halama** [comment]
yes I've seen that. So it look like there is also bug in error handling.

**Comment by pivnicek** [comment]
Ok, it works with a file that is actually there :-) 👍

**Comment by Halama** [comment]
i am trying to fix that error handling also

**Comment by Halama** [comment]
just to tell you that there were error

**Comment by Halama** [comment]
files expiration is related to this https://github.com/keboola/connection/issues/1080

**Comment by Halama** [comment]
image

**Comment by Halama** [comment]
error handler should be fixed now

**Comment by pivnicek** [comment]
Prima 👍

**Pull request merged**
